## configuration for the PAS request
pas_url: "https://compare.spirit.com/x/pas"
user_id: "d19eb199-19b0-49fa-af19-83406b44e751"
user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/83.0.4103.88 Mobile/15E148 Safari/604.1"
site_name: "spirit"
page_url: "https://www.spirit.com"
placement_id: "2713-3"
audiences: "{\"typeOne\":[\"1\",\"5\"],\"typeTwo\":[4]}"
startDate: "07/02/2020"
endDate: "07/05/2020"
adults: 1
origin: "ORD"
destination: "LAX"
isOneWay: "false"
