constrain_url: "https://www.clicktripz.com/api/integrations/v1/constrain"
user_id: "d83dc1ae-0126-47ac-9231-11aed27c6ba7"
session_id: "9cba75d4852f8fd8c50f8f92ee7bb677"
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 Chrome/83.0.4103.97 Safari/537.36"
site_name: "mapquest"
page_url: "https://www.mapquest.com"
authority_header: "www.clicktripz.com"