constrain_url: "https://www.clicktripz.com/api/integrations/v1/constrain"
user_id: "0446e614-0db4-4b4d-be74-c1095e1ee71e"
session_id: "9cba75d4852f8fd8c50f8f92ee7bb677"
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 Chrome/83.0.4103.97 Safari/537.36"
site_name: "mapquest"
page_url: "https://www.mapquest.com"
authority_header: "www.clicktripz.com"